### PR TITLE
Fix the bugs in the dust schemes.

### PR DESCRIPTION
**Pull request by zhanglikate**
Dust bugs reported by  ARL Barry.

### CODE REVIEW

**Comment by climbfuji** [comment]
Have you run tests with this bugfix? Do the regression tests run to completion, i.e. no crash?

**Comment by zhanglikate** [comment]
Hi Dom,

       Not yet. I just  test it in the workflow, and there  is not  problem to reproduce all the variables except dust1 (the bug  would impact).  But I will that. Can you tell me which . conf  (the rt.conf?) do you use for the RT  run? Should I repeat what you did？ Thanks.

./rt.sh -1  rt.conf

Li

**Comment by climbfuji** [comment]
> Hi Dom, Not yet. I just test it in the workflow, and there is not problem to reproduce all the variables except dust1 (the bug would impact). But I will that. Can you tell me which . conf (the rt.conf?) do you use for the RT run? Should I repeat what you did？ Thanks. ./rt.sh -1 rt.conf Li
> […](#)

I would run just
```
./rt.sh -l rt_ccpp_dev.conf -e
```
(don't forget to set `ACCNR`) It will probably say that the three chemistry tests failed, but if you look into the `log_hera.intel/rt_*` files for these jobs, you will hopefully see that only the files containing the arrays you expect to change have changed.

**Comment by zhanglikate** [comment]
Hi Dom,

       I did not see the “rt_chem.conf”  as before. And not use which one you combine it  into.

Li

**Comment by climbfuji** [comment]
> Hi Dom, I did not see the “rt_chem.conf” as before. And not use which one you combine it into. Li
> […](#)

Please use `rt_ccpp_dev.conf` as per my previous comment.

**Comment by zhanglikate** [comment]
Hi Dom,

        The RT run failed. Could you please help to check what happen: /scratch1/BMC/gsd-fv3-dev/lzhang/gsd-ccpp-chem/sorc/ufs-weather-model/tests/rt.log

   I just modify the ACCRN and the path of dprefix=/scratch1/BMC/gsd-fv3-dev/lzhang/EMC_FV3, beucase I don’t have the permission at  NCEPDEV. 

Li

**Comment by climbfuji** [comment]
> Hi Dom, The RT run failed. Could you please help to check what happen: /scratch1/BMC/gsd-fv3-dev/lzhang/gsd-ccpp-chem/sorc/ufs-weather-model/tests/rt.log I just modify the ACCRN and the path of dprefix=/scratch1/BMC/gsd-fv3-dev/lzhang/EMC_FV3, beucase I don’t have the permission at NCEPDEV. Li
> […](#)

```
cat /scratch1/BMC/gsd-fv3-dev/lzhang/gsd-ccpp-chem/sorc/ufs-weather-model/tests/log_hera.intel/compile_001.log
...
sbatch: error: Batch job submission failed: Invalid account or account/partition combination specified
```
I am out now, returning on May 9.

**Review by haiqinli — APPROVED** [review]

**Comment by zhanglikate** [comment]
Yes. I have  tested  that. No crash. Thanks.

**Review by DomHeinzeller — APPROVED** [review]
This change has been tested with the ufs-weather-model.

**Pull request merged**
